on:
  push:
    paths:
      - '**/*' # This will trigger the workflow on any file addition in any directory

jobs:
  check_new_file:
    runs-on: ubuntu-latest

    steps:
    - name: Check for New File
      id: file_check
      run: |
        # Check if any new files have been added in the push
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '.*'; then
          echo "New file(s) added."
          echo "::set-output name=new_file::true"
        else
          echo "No new files added."
          echo "::set-output name=new_file::false"
        fi

    - name: Notify on New File
      if: steps.file_check.outputs.new_file == 'true'
      run: |
        # Perform actions when a new file is added
        # For example, send a notification, build, or deploy
        echo "New file(s) added. Trigger your desired actions here."
